# configuration file for Travis-CI
# https://travis-ci.org

language: java

jdk:
  - oraclejdk8


before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# Gradlew
before_install:
 - chmod +x ./gradlew
  - pip install --user codecov
script:
  - ./gradlew jacocoTestReport coveralls
  
after_success: - bash <(curl -s https: //codecov.io/bash) 
               - codecov